title: STL Swift
description: iOS Developer Meetup Group in St. Louis
url: "https://stlswift.com"
baseurl: "" # Empty when using a custom domain

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - README.md
  - .github/ 